name: main
on:
  pull_request_target:
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows#pull_request_target
    types: [ labeled, unlabeled, opened, edited, closed, reopened, synchronize, locked, unlocked ]
    branches: [ main ]
  push:
    branches: [ main ]
  workflow_dispatch: # allows running this workflow manually from the Actions tab
jobs:
  notify_job:
    runs-on: ubuntu-latest
    steps:
      # https://docs.github.com/en/rest/reference/repos#create-a-repository-dispatch-event
      # PAT_TOKEN requires only "public_repo" scope
      - name: step-1
        run: |
          curl --no-progress-meter -u '${{ github.repository_owner }}:${{ secrets.PAT_TOKEN }}' -H 'Accept: application/vnd.github.v3+json' -H 'Content-Type: application/json' 'https://api.github.com/repos/${{ github.repository_owner }}/lccs_site/dispatches' --data '{"event_type": "${{ github.repository }}"}';
